### ISSUE TITLE
Find which specific google charts we are using to display info

### ISSUE THREAD

**Issue by taydougherty** [taydougherty/eeatz#12]

**Comment by luvkylo** [comment]
donut chart (google chart): 
- https://developers.google.com/chart/interactive/docs/gallery/piechart#donut 
- https://developers.google.com/chart/interactive/docs/roles#whatrolesavailable (custom tooltip)

Percentage bar (D3): 
- http://bl.ocks.org/jadiehm/7cc6b821d3df14280f33 
- https://bl.ocks.org/mbostock/3468167 (rounded cornors)
- `<script src="https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.8.0-alpha.1/d3-tip.js"></script>`
- look at "signed" js file for how to incorporate
